name: Daily MLB Email

on:
  schedule:
    - cron: "0 22 * * *"  # every day at 6 AM MST
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        working-directory: email
        env:
          EMAIL: ${{ secrets.EMAIL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          RECIPIENT: ${{ secrets.RECIPIENT }}  
       
        run: python main.py